import {
  androidstudio,
  atomone,
  aura,
  bbedit,
  darcula,
  dracula,
  duotoneDark,
  eclipse,
  githubLight,
  githubDark,
  materialLight,
  materialDark,
  sublime,
  tokyoNight,
  tokyoNightStorm,
  vscodeDark,
  xcodeDark,
  xcodeLight,
} from "@uiw/codemirror-themes-all";

export const ThemesList = [
  { name: "Android Studio", theme: androidstudio },
  { name: "Atomone", theme: atomone },
  { name: "Aura", theme: aura },
  { name: "Bbedit", theme: bbedit },
  { name: "Darcula", theme: darcula },
  { name: "Dracula", theme: dracula },
  { name: "Duotone Dark", theme: duotoneDark },
  { name: "Eclipse", theme: eclipse },
  { name: "Github Light", theme: githubLight },
  { name: "Github Dark", theme: githubDark },
  { name: "Material Light", theme: materialLight },
  { name: "Material Dark", theme: materialDark },
  { name: "Sublime", theme: sublime },
  { name: "Tokyo Night", theme: tokyoNight },
  { name: "Tokyo Night Storm", theme: tokyoNightStorm },
  { name: "Vscode Dark", theme: vscodeDark },
  { name: "Xcode Dark", theme: xcodeDark },
  { name: "Xcode Light", theme: xcodeLight },
];
